config/routes.rb
Rails.application.routes.draw do
  get 'index/index'
  get 'list/list'
  root "index#index", as: 'index'
  resources :properties
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/index/index.html.erb
<h1 class="title";>Ryokan</h1>

<button><%= link_to "List", list_list_path, :class => "header" %></button>

<h1>cunt</h1>
<p>Index page</p>

<!-- <form class="search">
  <label for="location" class="long_label">
    <input type="text" id="location" placeholder="Location" class="long_input"/>
  </label>
  <label for="price_min" class="long_label">
    <input type="text" id="price_min" placeholder="Minimum Price" class="long_input"/>
  </label>
  <label for="price_max" class="long_label">
    <input type="text" id="price_max" placeholder="Maximum Price" class="long_input"/>
  </label>
  <button type="submit" class="search_button" name="button" access="false" id="button">Search</button>
</form>
-->

<%= search_form_for @q, url: :index do |f| %>
  <%= f.label :address_cont, "Address" %>
  <%= f.search_field :address_cont %>
  <%= f.label :price, "Price" %>
  <%= f.text_field :price_gteq%>
  <%= f.label :to, "to" %>
  <%= f.text_field :price_lteq%>
  <%= f.label :price, "Size" %>
  <%= f.text_field :size_gteq%>
  <%= f.label :to, "to" %>
  <%= f.text_field :size_lteq%>
  <%= f.label :description_cont, "Description" %>
  <%= f.search_field :description_cont %>
  <%= f.label :date_listed_cont, "Date Listed" %>
  <%= f.search_field :date_listed_cont %>
  <%= f.submit %>
  <% end %>

  <% @properties.each do |property|%>
    <div class="card">
        <div class="container">
          <h4><b>Location</b></h4>
          <p><%= property.address %></p>
          <p>Price: <%= property.price %></p>
          <p>Size: <%= property.size %></p>
          <p>Description: <%= property.description %></p>
          <p>Date Listed: <%= property.date_listed %></p>
          <p>Source: <%= property.url %></p>
          <button>More Info</button>
        </div>
    </div>
    
    <% end %>